name: Generate Snake Animation

on:
  schedule:
    # Runs at every 12 hours (00:00 UTC and 12:00 UTC)
    - cron: "0 */12 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake Game from gif
        uses: Platane/snk@master
        id: snake

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # estes são os parâmetros padrão, você pode ajustá-los conforme necessário
          output: github-contribution-grid-snake.svg

      - name: Push Snake Game to the output branch
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: github-contribution-grid-snake.svg
